"""empty message

Revision ID: 552b66e00361
Revises: 35691a87b15e
Create Date: 2023-07-01 14:19:33.648413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552b66e00361'
down_revision = '35691a87b15e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_url', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('twitter_url', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               nullable=False)
        batch_op.create_unique_constraint(None, ['rif'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('salt',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('salt',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('location',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('phone')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('facebook_url')

    # ### end Alembic commands ###
