"""empty message

Revision ID: 594f1dfb62e6
Revises: 1fe2c04b5d11
Create Date: 2023-07-03 14:19:11.565188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594f1dfb62e6'
down_revision = '1fe2c04b5d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_image', schema=None) as batch_op:
        batch_op.drop_constraint('restaurant_image_restaurante_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_image', schema=None) as batch_op:
        batch_op.create_unique_constraint('restaurant_image_restaurante_id_key', ['restaurante_id'])

    # ### end Alembic commands ###
