"""empty message

Revision ID: c1c8ccf6c864
Revises: 552b66e00361
Create Date: 2023-07-01 20:10:48.624394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c8ccf6c864'
down_revision = '552b66e00361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_image')
    # ### end Alembic commands ###
